name: hizha_player
description: "Liquid Glass Player - Flutter Music Player"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.0
  file_picker: ^6.1.1
  window_manager: ^0.3.7
  flutter_acrylic: ^1.1.3
  google_fonts: ^6.1.0
  audio_video_progress_bar: ^2.0.1
  rxdart: ^0.27.7
  flutter_animate: ^4.3.0
  flutter_media_metadata: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
